#> -----------------------------------------------
#> Harvester Datapack
#> This code is protected by the GNU GPLv3 License
#> © 2020 Portyl Studios
#> https://portylstudios.com
#> -----------------------------------------------


#> install checker
# this code checks the install status of Harvester
#
# how to read $tc.version hashes:
# 10901 = v1.09.01 / v1.9.1


#> UPDATING: port all old release versions to v2.0.0
execute unless score $h.version TP_version matches 20000.. run function harvester:packages/update/v2.0.0

#> UPDATING: update v2.0.0 to v2.1.0
#execute if score $tc.version TP_version matches 20000..20001

#> install
execute unless score $h.version TP_version matches 20000.. run function harvester:packages/install

# WARNING: future features might not work
execute if score $h.version TP_version matches 20001.. run tellraw @a [{"text":""},{"text":" WARNING","color":"red","bold":"true","hoverEvent":{"action":"show_text","value":"Warning generated by Harvester"}},{"text":"\n This world was using a newer version of Harvester, some features may not be available.","color":"gray","hoverEvent":{"action":"show_text","value":"Warning generated by Harvester"}}]


#> End of file
#> -----------
