# notify
tellraw @a[tag=debug] [{"text":"","color":"gray","hoverEvent":{"action":"show_text","value":"Warning generated by Datapack Manager"}},{"text":"\n WARNING","color":"red","bold":"true"},{"text":"\n This world used to run an updated version of this datapack. Features added in future versions will not run on this version."}]
