# notify
tellraw @a[tag=debug] [{"text":"","color":"gray","hoverEvent":{"action":"show_text","value":"Alert generated by Datapack Manager"}},{"text":"\n ALERT","color":"gold","bold":"true"},{"text":"\n DatapackManager has been disabled."}]
title @a actionbar {"text":"Datapack uninstalled!"}
execute as @a at @s run playsound minecraft:entity.player.levelup player @s ~ ~ ~ 1 2 1
