#> -----------------------------------------------
#> <namespace> Datapack
#> This code is protected by the GNU GPLv3 License
#> © 2020 Portyl Studios
#> https://portylstudios.com
#> -----------------------------------------------


#> api
# this code controls the individual api scripts
#
# [$<main_pack>.api] [$<other_pack>.api] and [$api.<main_pack>.<other_pack>] should have the same values if the api is running


# enable api
scoreboard players set $api.<main_pack>.<other_pack> TP_version 101

# SUCCESS: tc h api active
tellraw @a [{"text":""},{"text":"\n SUCCESS","color":"green","bold":"true","hoverEvent":{"action":"show_text","value":"Success message generated by <main_pack> API"}},{"text":"\n Connected features between <main_pack> and <other_pack> is enabled.","color":"gray","hoverEvent":{"action":"show_text","value":"Success message generated by <main_pack> API"}}]


#> End of file
#> -----------
