# notify
tellraw @a [{"text":"","hoverEvent":{"action":"show_text","value":"Error generated by Datapack Manager"}},{"text":"\n ERROR","color":"dark_red","bold":"true"},{"text":"\n DatapackManager does not support this version of Minecraft. Uninstalling to prevent further unintended damage to your world.","color":"white"}]
