#> -----------------------------------------------
#> Tinkerer's Craft Datapack
#> This code is protected by the GNU GPLv3 License
#> © 2020 Portyl Studios
#> https://portylstudios.com
#> -----------------------------------------------


#> install checker
# this code checks the install status of Tinkerer's Craft
#
# how to read $tc.version hashes:
# 10901 = v1.09.01 / v1.9.1


#> UPDATING: port all old release versions to v2.0.0
execute unless score $tc.version TP_version matches 20000.. run function tinkererscraft:packages/update/v2.0.0

#> UPDATING: update v2.0.0 to v2.1.0
execute if score $tc.version TP_version matches 20000..20099 run function tinkererscraft:packages/update/v2.1.0

#> install
execute unless score $tc.version TP_version matches 20100.. if score $tc.version.override TP_config matches 0 run scoreboard players set $tc.version TP_version 20100
execute if score $tc.version TP_version matches 20100.. run function tinkererscraft:packages/install

# WARNING: future features might not work
execute if score $tc.version TP_version matches 20101.. if score $tc.debug TP_config matches 1..2 run tellraw @a [{"text":""},{"text":"\n WARNING","color":"red","bold":"true","hoverEvent":{"action":"show_text","value":"Warning generated by Tinkerer's Craft"}},{"text":"\n This world was using a newer version of Tinkerer's Craft, some features may not be available.","color":"gray","hoverEvent":{"action":"show_text","value":"Warning generated by Tinkerer's Craft"}}]


#> End of file
#> -----------
