#> -----------------------------------------------
#> Speedrun Tools Datapack
#> This code is protected by the GNU GPLv3 License
#> © 2020 Portyl Studios
#> https://portylstudios.com
#> -----------------------------------------------


#> install checker
# this code checks the install status of Speedrun Tools
#
# how to read $st.version hashes:
# 10901 = v1.09.01 / v1.9.1


#> fresh install
execute unless score $st.version TP_version matches 10000.. run function speedruntools:packages/update/v1.0.0

#> UPDATING: port all old release versions to v2.0.0
#execute unless score $st.version TP_version matches 20000.. run function speedruntools:packages/update/v2.0.0

#> UPDATING: update v2.0.0 to v2.0.1
#execute if score $st.version TP_version matches 20000..20001 run function speedruntools:packages/update/v2.0.1

#> UPDATING: update v2.0.1 to v2.1.0
#execute if score $st.version TP_version matches 20001..20100 run function speedruntools:packages/update/v2.1.0

#> install
execute unless score $st.version TP_version matches 10000.. run function speedruntools:packages/install

# WARNING: future features might not work
execute if score $st.version TP_version matches 10001.. run tellraw @a [{"text":""},{"text":" WARNING","color":"red","bold":"true","hoverEvent":{"action":"show_text","value":"Warning generated by Speedrun Tools"}},{"text":"\n This world was using a newer version of Speedrun Tools, some features may not be available.","color":"gray","hoverEvent":{"action":"show_text","value":"Warning generated by Speedrun Tools"}}]


#> End of file
#> -----------
