#> -----------------------------------------------
#> Tinkerer's Craft Datapack
#> This code is protected by the GNU GPLv3 License
#> © 2020 Portyl Studios
#> https://portylstudios.com
#> -----------------------------------------------


#> run
# run this to test all versions of Tinkerer's Craft

# clear chat
tellraw @a {"text":"\n\n\n\n\n\n\n\n\n\n"}

# start test in 3s
tellraw @a [{"text":""},{"text":"\n\n\n ALERT","color":"dark_red","bold":"true","hoverEvent":{"action":"show_text","value":"Alert generated by Tinkerer's Craft"}},{"text":"\n Tinkerer's Craft will automatically run version tests to check for compatibility. Do ","color":"red","hoverEvent":{"action":"show_text","value":"Alert generated by Tinkerer's Craft"}},{"text":"NOT","color":"red","bold":"true","underlined":"true","hoverEvent":{"action":"show_text","value":"Alert generated by Tinkerer's Craft"}},{"text":" close Minecraft, disable Tinkerer's Craft, or use any features provided by Tinkerer's Craft until the tests are complete.\n\n","color":"red","hoverEvent":{"action":"show_text","value":"Alert generated by Tinkerer's Craft"}}]


#> testing
# 3s setup delay + 9s testing delay + 1s buffer + 7s testing delay + 1s buffer


# setup
function tinkererscraft:packages/tests/setup

# start tests
execute if score $global.version.override TP_config matches 1 run schedule function tinkererscraft:packages/tests/schedule/global 3s

# start tests after first test
execute if score $tc.version.override TP_config matches 1 run schedule function tinkererscraft:packages/tests/schedule/tc 13s

# finish tests
schedule function tinkererscraft:packages/tests/finish 21s


#> End of file
#> -----------
