# This file is automatically generated. Do not edit.
# function endermitescriptframework:scripts/%NAME%/_help
function endermitescriptframework:scripts/blinkingredstonelamp/_help
function endermitescriptframework:scripts/drivablevehicles/_help
function endermitescriptframework:scripts/trafficlight/_help