#> -----------------------------------------------
#> Speedrun Tools Datapack
#> This code is protected by the GNU GPLv3 License
#> © 2020 Portyl Studios
#> https://portylstudios.com
#> -----------------------------------------------


#> uninstall
# this code is the uninstallation confirmation message

tellraw @s [{"text":""},{"text":"\n\n\n ALERT","color":"dark_red","bold":"true","hoverEvent":{"action":"show_text","value":"Alert generated by Speedrun Tools"}},{"text":"\n Uninstalling this datapack will revert the world to its original state.","color":"red","hoverEvent":{"action":"show_text","value":"Alert generated by Speedrun Tools"}},{"text":"\n\n Are you sure that you want to uninstall Speedrun Tools?","color":"dark_red"},{"text":"\n "},{"text":"YES","color":"green","bold":"true","clickEvent":{"action":"run_command","value":"/function speedruntools:packages/uninstall"}},{"text":" "},{"text":"NO","color":"red","bold":"true","clickEvent":{"action":"run_command","value":"/function speedruntools:packages/uninstall_cancelled"}}]


#> End of file
#> -----------
