# notify
tellraw @a [{"text":"","hoverEvent":{"action":"show_text","value":"Alert generated by Datapack Manager"}},{"text":"\n ALERT","color":"gold","bold":"true"},{"text":"\n DatapackManager has been disabled.","color":"gray"}]

# disable pack
datapack disable "file/datapackmanager-1.19"
