# This file is automatically generated. Do not edit.
# execute if entity @s[tag=!ESF_processed] run function endermitescriptframework:scripts/%NAME%/_processor
execute if entity @s[tag=!ESF_processed] run function endermitescriptframework:scripts/blinkingredstonelamp/_processor
execute if entity @s[tag=!ESF_processed] run function endermitescriptframework:scripts/drivablevehicles/_processor
execute if entity @s[tag=!ESF_processed] run function endermitescriptframework:scripts/trafficlight/_processor