# notify
tellraw @s [{"text":"","color":"gray","hoverEvent":{"action":"show_text","value":"Message generated by Datapack Manager"}},{"text":"\n Datapack Manager","color":"gold","bold":true},{"text":"\n Triggered: dm_uninstall"},{"text":"\n"}]

function datapackmanager-1.21:packages/effects/ui/jingle

# send event
tag @s add DM_command_uninstall
scoreboard players operation EVENT$command.uninstall DatapackManager = BOOL$true DatapackManager

# stop after 2 seconds
schedule function datapackmanager-1.21:root/commands/uninstall- 2s