# notify

tellraw @s [{"text":"","color":"gray","hoverEvent":{"action":"show_text","value":"Message generated by Datapack Manager"},"hover_event":{"action":"show_text","value":"Message generated by Datapack Manager"}},{"text":"\n Datapack Manager","color":"gold","bold":true},{"text":"\n Triggered: dm_help"},{"text":"\n\n [*] Requires that permission tag to use.","italic":true},{"text":"\n\n Available commands:"}]

tellraw @s [{"text":"","color":"gray","hoverEvent":{"action":"show_text","value":"Message generated by Datapack Manager"},"hover_event":{"action":"show_text","value":"Message generated by Datapack Manager"}},{"text":" - "},{"text":"dm_help","color":"white"},{"text":" -> Displays this help message."}]

tellraw @s [{"text":"","color":"gray","hoverEvent":{"action":"show_text","value":"Message generated by Datapack Manager"},"hover_event":{"action":"show_text","value":"Message generated by Datapack Manager"}},{"text":" - "},{"text":"dm_info","color":"white"},{"text":" -> Displays information about Datapack Manager."}]

tellraw @s [{"text":"","color":"gray","hoverEvent":{"action":"show_text","value":"Message generated by Datapack Manager"},"hover_event":{"action":"show_text","value":"Message generated by Datapack Manager"}},{"text":" - "},{"text":"dm_version","color":"white"},{"text":" -> Displays the current minecraft version."}]

tellraw @s[tag=DM_admin] [{"text":"","color":"gray","hoverEvent":{"action":"show_text","value":"Message generated by Datapack Manager"},"hover_event":{"action":"show_text","value":"Message generated by Datapack Manager"}},{"text":" - "},{"text":"dm_config","color":"white"},{"text":" ["},{"text":"DM_admin","color":"red"},{"text":"] -> Displays config options for all supported datapacks."}]

tellraw @s[tag=DM_admin] [{"text":"","color":"gray","hoverEvent":{"action":"show_text","value":"Message generated by Datapack Manager"},"hover_event":{"action":"show_text","value":"Message generated by Datapack Manager"}},{"text":" - "},{"text":"dm_uninstall","color":"white"},{"text":" ["},{"text":"DM_admin","color":"red"},{"text":"] -> Displays UI for uninstalling supported datapacks."}]

tellraw @s [{"text":""}]

function datapackmanager-1.21:packages/effects/ui/jingle