#> -----------------------------------------------
#> Tinkerer's Craft Datapack
#> This code is protected by the GNU GPLv3 License
#> © 2020 Portyl Studios
#> https://portylstudios.com
#> -----------------------------------------------


#> version checker
# this code runs to check which version the game is running in
#
# it disables the datapack if the version is not supported, preventing advancements or anything to function and mess with the game in any way
# it also comes with the capability to target specific minecraft versions and only enable certain code for certain versions
# afaik this feature was invented by me, I have not seen anyone do this before
#
# credit goes to Ryuggo for the concept [https://www.planetminecraft.com/member/ryuggo]
# taken and edited from his pocket dimensions datapack [https://www.planetminecraft.com/data-pack/mcr-pocket-dimension]


# init
execute unless score $global.version TP_version matches 112.. if score $global.version.override TP_config matches 0 run scoreboard players set $global.version TP_version 112

# version checker
execute unless score $global.version TP_version matches 113.. if score $global.version.override TP_config matches 0 run function tinkererscraft:packages/version_checker/1.13
execute unless score $global.version TP_version matches 114.. if score $global.version.override TP_config matches 0 run function tinkererscraft:packages/version_checker/1.14
execute unless score $global.version TP_version matches 115.. if score $global.version.override TP_config matches 0 run function tinkererscraft:packages/version_checker/1.15
execute unless score $global.version TP_version matches 116.. if score $global.version.override TP_config matches 0 run function tinkererscraft:packages/version_checker/1.16
execute unless score $global.version TP_version matches 117.. if score $global.version.override TP_config matches 0 run function tinkererscraft:packages/version_checker/1.17


# ERROR: unsupported version
execute unless score $global.version TP_version matches 116.. if score $tc.debug TP_config matches 1..3 run tellraw @a [{"text":""},{"text":"\n ERROR","color":"dark_red","bold":"true","hoverEvent":{"action":"show_text","value":"Error generated by Tinkerer's Craft"}},{"text":"\n You must use Minecraft version 1.16 or higher for Tinkerer's Craft to run!","color":"gray","hoverEvent":{"action":"show_text","value":"Error generated by Tinkerer's Craft"}}]
execute unless score $global.version TP_version matches 116.. if score $global.version.override TP_config matches 0 run datapack disable "file/tinkererscraft"

#> install_checker
execute if score $global.version TP_version matches 116.. run function tinkererscraft:packages/install_checker

# WARNING: future version detected
execute if score $global.version TP_version matches 118.. if score $tc.debug TP_config matches 1..2 run tellraw @a [{"text":""},{"text":"\n WARNING","color":"red","bold":"true","hoverEvent":{"action":"show_text","value":"Warning generated by Tinkerer's Craft"}},{"text":"\n This world was played in a newer version of Minecraft, some features may not be available.","color":"gray","hoverEvent":{"action":"show_text","value":"Warning generated by Tinkerer's Craft"}}]


#> End of file
#> -----------
