# notify
tellraw @a [{"text":"","hoverEvent":{"action":"show_text","value":"Alert generated by Datapack Manager"}},{"text":"\n ALERT","color":"gold","bold":"true"},{"text":"\n Loaded the updated configuration file.","color":"gray"}]

# default values
scoreboard players set VERSION$minecraft.backward DatapackManager 13
scoreboard players operation VERSION$minecraft.forward DatapackManager = VERSION$minecraft.backward DatapackManager
scoreboard players set VERSION$datapack.current DatapackManager 10000

# load
function datapackmanager:config
