#> -----------------------------------------------
#> Harvester Datapack
#> This code is protected by the GNU GPLv3 License
#> © 2020 Portyl Studios
#> https://portylstudios.com
#> -----------------------------------------------


#> api install (references: tinkererscraft/packages/api/api_checker_h)
# this code controls the individual api scripts
#
# [$tc.api] [$h.api] and [$api.tc.h] should have the same values if the api is running


# enable api
scoreboard players set $api.tc.h TP_version 201

# start loop
function harvester:packages/api/tinkererscraft/update_item

# SUCCESS: tc h api active
tellraw @a [{"text":""},{"text":"\n SUCCESS","color":"green","bold":"true","hoverEvent":{"action":"show_text","value":"Success message generated by Tinkerer's Craft API"}},{"text":"\n Connected features between Tinkerer's Craft and Harvester is enabled.","color":"gray","hoverEvent":{"action":"show_text","value":"Success message generated by Tinkerer's Craft API"}}]


#> End of file
#> -----------
