# notify
tellraw @a [{"text":"","color":"gray","hoverEvent":{"action":"show_text","value":"Message generated by Datapack Manager"}},{"text":"\n Datapack Manager","color":"gold","bold":true},{"text":"\n Playing on Minecraft 1."},{"score":{"name":"VERSION$minecraft.current","objective":"DatapackManager"}},{"text":"\n"}]

function datapackmanager-1.20:packages/effects/ui/jingle