# notify
tellraw @s [{"text":"","color":"gray","hoverEvent":{"action":"show_text","value":"Message generated by Datapack Manager"}},{"text":"\n Datapack Manager","color":"gold","bold":true},{"text":"\n Triggered: dm_config"},{"text":"\n"}]

function datapackmanager-1.21:packages/effects/ui/jingle

# send event
function datapackmanager-1.21:root/events/commands/config/send